### ISSUE TITLE
some alignment issues

### ISSUE THREAD

**Issue by samoht** [pqwy/notty#2]
Hi, first of all thanks for that amazing library. It's like magic, but better. 

When running `./runes.native` I got some alignement issues:

![screen shot 2016-02-11 at 07 43 48](https://cloud.githubusercontent.com/assets/103693/12971471/655f50fe-d093-11e5-930c-0be86627e828.png)

Anything special to report to help debugging that? I'm running on OSX 10.10.5 and notty is built from master.

**Comment by dbuenzli** [comment]
@samoht nothing can be done for this. It hits the limits of what you can do in terminal without having information back from the text layout engine. Read [here](http://erratique.ch/software/uucp/doc/Uucp.Break.html#terminal_width) for David's take on this.

David, maybe you should add a preamble that this is expected to break and how, otherwise you are constantly going to get reports about this.

**Comment by samoht** [comment]
ack. A simple way to fix this would be to split the output of `runes` into things which usually don't break and things which might break.

**Comment by pqwy** [comment]
Yeah, [abugidas](https://en.wikipedia.org/wiki/Abugida) (Tamil, Kannada and Devanagari above) destroy just about all alphabet-centric spacing and layout assumptions. They are rendered quite differently by different text layout engines.

I'm pleasantly surprised by the robustness of Arabic and Hebrew, though.

Thanks for the report! Added a note to `runes`.
