### ISSUE TITLE
What is Gen_output for?

### ISSUE THREAD

**Issue by yminsky** [pqwy/notty#25]
I'm writing an Async driver for Notty, and I noticed that the Lwt driver use the Gen_output module for...something, but it wasn't clear what. I replicated it:

https://github.com/yminsky/notty_async/blob/master/src/notty_async.ml#L155

But it's not obvious to me that it's actually necessary. I'd be curious to understand what its purpose is.

**Comment by pqwy** [comment]
The purpose is to reuse the implementation of a handful of operations that exist outside of the `Term` interface, to give them uniform behaviour. These are the [_inline_](http://pqwy.github.io/notty/doc/Notty_unix.html) operations.

You have [`output`](https://github.com/pqwy/notty/blob/b598978a02a6796b61ac3982b9a3cebc87863b9c/unix/notty_unix.ml#L50) which takes care of selecting the `Cap` and maintaining an internal write buffer; [`output_image_size`](https://github.com/pqwy/notty/blob/b598978a02a6796b61ac3982b9a3cebc87863b9c/unix/notty_unix.ml#L55) which checks terminal size, gives that to the client function, then renders only the part of the result that fits; [`two`](https://github.com/pqwy/notty/blob/b598978a02a6796b61ac3982b9a3cebc87863b9c/unix/notty_unix.ml#L64) [`commands`](https://github.com/pqwy/notty/blob/b598978a02a6796b61ac3982b9a3cebc87863b9c/unix/notty_unix.ml#L67) for moving the cursor; and an [output variant](https://github.com/pqwy/notty/blob/b598978a02a6796b61ac3982b9a3cebc87863b9c/unix/notty_unix.ml#L70) that takes an `image`. The entire thing is named "Generic Output" because it was generic for the outputs so far.

It's a bit of glue that ends up being similar between pure `unix` and `Lwt_unix`. The important shared logic is all in the `Notty` module, so if `Gen_output` doesn't fit `Async` API or idioms, you can just implement the inline output directly.
